version: "3"
services:
  dnsmasq: # https://github.com/4km3/docker-dnsmasq
    # cap_add:
    #   - NET_ADMIN
    container_name: dnsmasq
    image: 4km3/dnsmasq:2.85-r2
    network_mode: host
    # ports:
    #   - "53:53/udp"
    #   - "53:53/tcp"
    privileged: true
    restart: unless-stopped
    volumes:
      - /docker/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro

    # mosquitto: # https://github.com/docker-library/official-images/blob/master/library/eclipse-mosquitto
    #     # command: tail -F anything
    #     container_name: mosquitto
    #     image: eclipse-mosquitto:2.0.12-openssl # 2.0.11-openssl
    #     networks:
    #         - mosquitto
    #     ports:
    #         # - 127.0.0.1:1883:1883
    #         - 1883:1883
    #         - 8883:8883
    #         - 8884:8884
    #     restart: unless-stopped
    #     volumes:
    #         - /docker/mosquitto/config:/mosquitto/config
    #         - /docker/mosquitto/ssl:/mosquitto/ssl
    #         - /mnt/ssd/mosquitto/data:/mosquitto/data
    #         - /mnt/ssd/mosquitto/log:/mosquitto/log

  homeassistant: # https://github.com/home-assistant/core/pkgs/container/raspberrypi4-homeassistant/versions
    container_name: homeassistant
    # depends_on:
    #   - mariadb
    #   - mosquitto
    image: "ghcr.io/home-assistant/raspberrypi4-homeassistant:2021.10.6" # 2021.9.7 2021.9.5 2021.8.8
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - /docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
